version: '3'
services:
  php:
    container_name: application
    build: docker/app
    volumes:
      - .:/var/www
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 9916:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - php
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: music-composer
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3701:3306


  phpmyadmin:
    image: phpmyadmin
    container_name: admin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    depends_on:
      - db
    ports:
      - 2080:80
    volumes:
      - /sessions