version: '3'
services:
  php:
    container_name: app
    build: docker/app
    volumes:
      - .:/var/www
  nginx:
    image: nginx
    container_name: server
    ports:
      - 9901:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - php
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: frontlaravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3400:3306


  phpmyadmin:
    image: phpmyadmin
    container_name: adminphp
    environment:
      - PMA_ARBITRARY=1
    restart: always
    depends_on:
      - db
    ports:
      - 1080:80
    volumes:
      - /sessions

  react:
    container_name: react
    build: ./src/frontend
    ports:
      - '3007:3000'
    tty: true
