version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Build application"
          command: "echo Building application"

  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test application"
          command: "echo Testing application"

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build